#Docker compose is a tool which is used to managae and execute multi cntainer applications
#we create our own bridge network to communicate with components
#volumes is used for stateful applications like DB apps which can be managed by docker itself. 
#When containers deleted and re-created still data would't be lost
networks:
  default:
    driver: bridge
    name: roboshop
    #external: true #If network already created using docker network create
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:  # these are creating volume like docker volume create rabbitmq
services:
  mongodb:
    image: johnson0309/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: johnson0309/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data            #/data is the dir where docker stores the volumes
  user:
    image: johnson0309/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  cart:
    image: johnson0309/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  mysql:
    image: johnson0309/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: johnson0309/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: johnson0309/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - rabbitmq
    - cart
    - user
  frontend: 
    image: johnson0309/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment