#For MongoDB we can use officila image and load the data. 
#When used officila it will auto perform the installation and start the mongodb
#Usually docker have one path where we can put our data so that it will auto load it.
FROM mongo:7.0
COPY *.js /docker-entrypoint-initdb.d